### ISSUE TITLE
Get returns any if the needle is incorrect

### ISSUE THREAD

**Issue by michaelKurowski** [geoffreytools/type-lenses#1]
When the path passed to needle points to a place that does not exist on the type, it returns `any`. My expectation would be for it to return `never` or throw an error as otherwise it essentially ends up with a silent pass from the types point of view.

**Comment by geoffreytools** [comment]
Hi,

The return type when the needle is not found is unspecified, but yes it should be `never`.

I can make this work for most cases but I may fail to reliably reject bad free types because some built-in type combinations are structurally compatible.

Type checking the path in `Get` would most likely make it impossible to use `Get` when the `Haystack` is generic, because the type checker will not substitute the generic for its type constraint when performing checks, it's simply going to give up with a cryptic error. A workaround is to also accept an optional `Model` as I did with [free-types/Match](https://github.com/geoffreytools/free-types/blob/public/doc/Documentation.md#matcht-p-r-k-m), but this API is quite frustrating to use to be honest because you always forget you have to use it and repeating the type constraint just feels bad.

I'm thinking that `Lens` could do the type checking because you are not likely to use it with generics: you create a Lens with an interface in mind and that could be the `Model`. When a `Model` is supplied, the type constraint for the query would try to apply `Get<Query, Model>` and if the call returns `never` it would return a union of valid paths to try instead.

**Comment by geoffreytools** [comment]
type-lenses now optionally perform type checking on `Lens`.
